### ISSUE TITLE
Number format strings

### ISSUE THREAD

**Issue by otherjoel** [simmone/racket-simple-xlsx#10]
Hello again and thanks for this great package! 

In addition to existing date/number format options, it would be nice to specify [Excel format code strings][1] directly. For example `_(* #,##0_);_(* (#,##0);_(* "-"??_);_(@_)` for accounting number format.

I believe the XML file format itself supports these strings. So you would not have to parse them in your library. Simply pass them through to the `.xlsx` file XML.

[1]: https://support.microsoft.com/en-us/office/number-format-codes-5026bbd6-04bc-48cd-bf33-80f18b4eae68?ui=en-us&rs=en-us&ad=us

**Comment by simmone** [comment]
Sorry, a little busy these time.

I'll add this function part as soon as I can.

**Comment by simmone** [comment]
Fixed, please update package and verify.

Note that, I find some format code should use entity to replace, like " should replace with $quote;

**Comment by simmone** [comment]
forget add sample code, add formatCode:

 ```
(send xlsx add-data-sheet-cell-style! 
#:sheet_name "DataSheetWithStyle2" #:cell_range "G1" 
#:style '((formatCode . "@__&quot;means&quot;__@")))

  (send xlsx add-data-sheet-col-style! 
#:sheet_name "DataSheetWithStyle2" #:col_range "E-F"
#:style '((formatCode . "￥#,##0.00;[Red]￥-#,##0.00")))

```
