### ISSUE TITLE
Number format multiple sheets

### ISSUE THREAD

**Issue by petterpripp** [simmone/racket-simple-xlsx#15]
There is an bug when using multiple sheets and number formating. 
If number formating is used at first sheet , then number formating does not work properly on second sheet.

Below is example of code with bug:

```racket
#lang racket

(require simple-xlsx)

(define xlsx (new xlsx%))

(send xlsx add-data-sheet
      #:sheet_name "s1"
      #:sheet_data '( ("number") (1) (2)))

; BUG: numberPrecision on sheet "s2" does not work properly.
; Comment out this call, and numberPrecision on sheet "s2" will work.
(send xlsx add-data-sheet-col-style!
      #:sheet_name "s1"
      #:col_range "1"
      #:style '((numberPrecision . 0)))

(send xlsx add-data-sheet
      #:sheet_name "s2"
      #:sheet_data '( ("number") (7.89) (3.21)))

(send xlsx add-data-sheet-col-style!
      #:sheet_name "s2"
      #:col_range "1"
      #:style '((numberPrecision . 2)))

(write-xlsx-file xlsx "/tmp/bug.xlsx")
```

**Comment by simmone** [comment]
Got it! A little busy this week, I'll fix it as soon as I can.

**Comment by simmone** [comment]
Fixed,  please update the package to test.

**Comment by petterpripp** [comment]
Thanks, Number formating OK  :+1: 

Howeever on sheet "s2" the column now have background colour "grey", and no border.
Workaround is add to style: 
```racket
(backgroundColor . "ffffff") (borderStyle . thin) (borderColor . "b2b2b2")
```

**Comment by simmone** [comment]
Fixed, thank you again for report, please update package to verify.

Petter Olav Pripp <notifications@github.com> 于2020年12月11日周五 上午9:20写道：

**Comment by petterpripp** [comment]
Perfect! Thank you very much :1st_place_medal: :1st_place_medal: :1st_place_medal:
