### ISSUE TITLE
Small bug in reader (Generated excel files)

### ISSUE THREAD

**Issue by lannydpittman** [simmone/racket-simple-xlsx#17]
As a note, I have found a small issue with the reader - the regex in `load-sheet` fails on some excel files created by a program other than excel (in my case, Hubspot) , since in the generated excel, the worksheet XML file may look something like this:

Example: *Generated file* (multiple lines)
```xml
<?xml version="1.0" encoding="UTF-8"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><dimension ref="A1"/> (etc....)
<row r="1">
<c r="A1" ...>
<row r="2">
<c r="A2" ...>
```

Example: *File created by Excel* (all on 2 lines)
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeD  etc....
```

As can be seen, the generated file will possibly have a \n or a \r before the start of a row.
I suspect that the below line of code is the culprit, as the regex will not allow the \n or \r instead of the space before the `<row r="1">`. 
https://github.com/simmone/racket-simple-xlsx/blob/4db2b2eb3e66f1bbc4c8cfff268697085891a9bc/simple-xlsx/reader.rkt#L170

As a quick fix, though, you can simply open the excel file and save it a few times. Excel will then 'fix' the xml so it is all on one line and the `load-sheet` method will work.

**Comment by simmone** [comment]
Thank you, it's a bug indeed.
The current version's simple-xlsx is not deal xml properly, combine xml interperter and hand writing code, it's buggy.
Now I'm working on a completely new version of simple-xlsx(not compatible with current version), completely rewrite all the code, remove many bugs include this one.
So, I wish when the new version's simple-xlsx is done, can you do me a favor, to upgrade and let me know the new one is dealing the xlsx file correctly.
Thanks.

**Comment by simmone** [comment]
Hi, newest version is updated. You can updated to newest version. 
But this version is complete rewrite, it's not back compatible.
If you decide to update, you should read docs first, your code need to modify a little.
Thank you for use this package, if you have any need, please let me know.
