### ISSUE TITLE
Doc not rendered because the build fails

### ISSUE THREAD

**Issue by sorawee** [simmone/racket-simple-xlsx#18]
The recent change causes the build to fail

```
raco setup: error: during making for <pkgs>/simple-xlsx/simple-xlsx/example
raco setup:   /home/root/user/.local/share/racket/8.7/pkgs/simple-xlsx/simple-xlsx/example/example.rkt:7:17: xlsx%: unbound identifier
raco setup:     in: xlsx%
raco setup:     compiling: <pkgs>/simple-xlsx/simple-xlsx/example/example.rkt
```

which causes the doc to fail to render at

https://docs.racket-lang.org/simple-xlsx/index.html

Note that it is salvaged automatically, and is now available at https://docs.racket-lang.org/simple-xlsx@simple-xlsx/index.html

**Comment by simmone** [comment]
sorry, I'm doing a big version update for simple-xlsx(not back compatible).

I need some time to correct these issues, thank you for use simple-xlsx
package.

It's a brand new version, if encounter some problem, let me know, thanks.

sorawee ***@***.***> 于 2022年12月16日周五 17:46写道：

**Comment by simmone** [comment]
en...package building seems stop working, I fix and updated, but package can't updated, still waiting.

**Comment by simmone** [comment]
Package updated, this problem is fixed.
