### ISSUE TITLE
adding a static named range breaks lookup by sheet name

### ISSUE THREAD

**Issue by jorritvm** [simmone/racket-simple-xlsx#20]
Let's say I want to get the amount of rows for any sheet of my excel file.

I could call the following procedure with "sheet1" as argument.
```
    (define (get-row-count sheet)
      (define n-rows 0)
      (read-xlsx
       railway-configuration-file
       (lambda ()
         (set! n-rows (get-sheet-name-rows-count sheet))))
      n-rows)
```

This works, until you create a static named range in the excel file, which results in an error:
```list-ref: index too large for list``` 

If you create a dynamic named range, this does not seem to bother the library.

**Comment by jorritvm** [comment]
after some more debugging rephrased my original issue

**Comment by simmone** [comment]
Get it! Please give me some time. Sorry,  a little busy on work recently.

Jorrit Vander Mynsbrugge ***@***.***> 于2023年7月11日周二 01:55写道：

**Comment by simmone** [comment]
Thank your long wait, I have comple a major update, and I test a simple sheet rows sum, seems no problem.

```
               (let loop ([sheet_names (get-sheet-name-list)]
                          [rows_sum 0])
                 (if (not (null? sheet_names))
                     (loop (cdr sheet_names)
                           (+ rows_sum (get-sheet-name-rows-count (car sheet_names))))
                     rows_sum))
```
Please update package and verify, works or not, please let me know, thank you.
