### ISSUE TITLE
Reader not picking up the full content of a <cell>

### ISSUE THREAD

**Issue by lannydpittman** [simmone/racket-simple-xlsx#21]
Racket version 8.11.1

Expected behavior:
The full cell value (as a string) will be returned.

Problem:
Cells containing a < or > do not read properly.
This is an issue for me since I am trying to generate excel documents based on information from an API by replacing \<value\> with the appropriate value from the API. 

Steps to reproduce:

`read-xlsx` an .xlsx file that contains cell values surrounded by < and >, like \<foo\>.
Like so:
``` racket
(write-xlsx

 "angles.xlsx"

 (lambda ()

   (add-data-sheet "Sheet1" '(("<test>" "<foo> " " <baz>")
                              ("< bar>" "< fro >" "<bas >")
                              ("<maybe" "<< not >>" "show>")))
   ))
(define sheet-names #f)
(define input #f)
(read-xlsx "angles.xlsx"
             (λ ()
               (set! sheet-names (get-sheet-name-list)) ;get the sheet names            
               (set! input                       ;get all the sheet information
                     (for/list ([sheet sheet-names])
                       (with-sheet-name
                           sheet
                         (λ ()
                           (get-rows)))
                       )))    
               )
input
```
the resulting response is puzzling, to say the least:

``` racket
'((("<" "<" " ")
   ("<" "<" "<")
   ("<" "<" "show")))
```

**Comment by simmone** [comment]
Sorry for a late reply, because these days in on vacation.

This bug is my another package: simple-xml's fault, it don't deal load the
special chars correctly.

You can update the simple-xml to fix it.

raco pkg update simple-xml.

Thank your usage and bug report, if meet any problems, let me know.

lannydpittman ***@***.***> 于2024年1月23日周二 22:15写道：
