### ISSUE TITLE
Lists must be the same length when used in add-data-sheet

### ISSUE THREAD

**Issue by lannydpittman** [simmone/racket-simple-xlsx#22]
Would it be possible to improve the `add-data-sheet` function so that it doesn't care how long each element is, it just pads them with the dummy value `""` so that they are all equal length beforehand?

Either this could be integrated into `add-data-sheet`, or you could just offer another function in the simple-xlsx package that pads these lists.

Here is just a quick example of how this might work:

``` racket
(define (pad-lists lst-of-lists pad-value)
  ;; Find the maximum length of lists
  (define max-length
    (foldl (λ (lst acc)
             (max acc (length lst))) 0 lst-of-lists))

  ;; Pad each list to the maximum length
  (define padded-lists
    (map (λ (lst) (append lst (make-list (- max-length (length lst)) pad-value)))
         lst-of-lists))

  padded-lists)
```

Usage:

``` racket
(define test-list
  '((1 3 5 3)
    (2 5 2)
    (1 3 2)
    (2)
    ))
(pad-lists test-list "")
```

**Comment by simmone** [comment]
Good suggestion!

I have add a optional keyword argument to add-data-sheet.

#:fill? value (value can be string? or number? or date?, default is "")

Code is complete, but I find package can't be upgraded.

I republish the package, maybe need to wait tomorrow can be upgraded.

lannydpittman ***@***.***> 于2024年1月24日周三 00:34写道：

**Comment by simmone** [comment]
Update by raco pkg update simple-xlsx.

Encounter any problems, let me know, thank you.
