### ISSUE TITLE
Font, date and number format

### ISSUE THREAD

**Issue by petterpripp** [simmone/racket-simple-xlsx#3]
Nice library, have some feature requests for write function:

- Font name
- Font size
- Font Bold 
- Date format
- Number format

That would make the library very useful for writing Excel reports.

**Comment by simmone** [comment]
Very glad to hear the feature requests.

I'll work for it.

2018-06-05 15:03 GMT+08:00 Petter Olav Pripp <notifications@github.com>:

**Comment by simmone** [comment]
Added various styles and date data type to data sheet.

Please update package and view the docs about how to add styles to data sheet.
