### ISSUE TITLE
"Freeze panes" support

### ISSUE THREAD

**Issue by otherjoel** [simmone/racket-simple-xlsx#5]
Is it possible to set the "freeze panes" on a sheet?

**Comment by simmone** [comment]
Of course! I'll work for it.

**Comment by simmone** [comment]
updated: raco pkg update simple-xlsx 

usage:

;; freeze 1 row and 1 col
(send xlsx set-data-sheet-freeze-pane! #:sheet_name "DataSheet" #:range '(1 . 1))

**Comment by simmone** [comment]
No, it's not work in windows, please wait.

**Comment by simmone** [comment]
done, please update package to try it.

**Comment by otherjoel** [comment]
This works great, thank you!
