### ISSUE TITLE
Column or row styles

### ISSUE THREAD

**Issue by otherjoel** [simmone/racket-simple-xlsx#7]
Is there a good way to specify a style for an entire row? Or for an entire column?

**Comment by simmone** [comment]
done, please update and verify.

add three style setting methods:

add-data-sheet-row-style!
add-data-sheet-col-style!
set-data-sheet-row-height!

  (send xlsx add-data-sheet-row-style! #:sheet_name "DataSheetWithStyle2" #:row_range "1-3" #:style '( (backgroundColor . "00C851") ))
  (send xlsx add-data-sheet-col-style! #:sheet_name "DataSheetWithStyle2" #:col_range "1-6" #:style '( (backgroundColor . "AA66CC") ))

  (send xlsx set-data-sheet-row-height! #:sheet_name "DataSheetWithStyle2" #:row_range "2-4" #:height 30)

**Comment by otherjoel** [comment]
This is very useful, however it doesn't quite work the way I expect.

See example.

```racket
#lang racket

(require simple-xlsx racket/date)

(let ([xlsx (new xlsx%)]
      [sheet_data
       (list
        (list "month/brand" "201601" "201602" "201603" "201604" "201605")
        (list "CAT" 100 300 200 0.6934
              (seconds->date (find-seconds 0 0 0 17 9 2018)))
        (list "Puma" 200 400 300 139999.89223
              (seconds->date (find-seconds 0 0 0 18 9 2018)))
        (list "Asics" 300 500 400 23.34
              (seconds->date (find-seconds 0 0 0 19 9 2018)))
        )])

  ;; add data
  (send xlsx add-data-sheet #:sheet_name "DataSheet" #:sheet_data sheet_data)

 ;; (Part 1) Set date formats — no color info...
  (send xlsx add-data-sheet-cell-style! #:sheet_name "DataSheet"
        #:cell_range "F2-F2"
        #:style '( (dateFormat . "yyyy-mm-dd") ))
  (send xlsx add-data-sheet-cell-style! #:sheet_name "DataSheet"
        #:cell_range "F3-F3"
        #:style '( (dateFormat . "yyyy/mm/dd") ))
  (send xlsx add-data-sheet-cell-style! #:sheet_name "DataSheet"
        #:cell_range "F4-F4"
        #:style '( (dateFormat . "yyyy年mm月dd日") ))

  ;; (Part 2) Set background color for entire rows and columns
  (send xlsx add-data-sheet-row-style! #:sheet_name "DataSheet" #:row_range "1-3" #:style '( (backgroundColor . "FEFFC1") ))
  (send xlsx add-data-sheet-col-style! #:sheet_name "DataSheet" #:col_range "1-6" #:style '( (backgroundColor . "0000FF") ))

  (write-xlsx-file xlsx "test.xlsx"))
```

I would expect the “Part 2” calls to override the background color for all rows/columns that they touch, since they come last.

However, what happens is the following:

![image](https://user-images.githubusercontent.com/1553115/63724873-6f191680-c81e-11e9-9d74-8e2c380d729d.png)

Interestingly, the result is the same even if the “Part 2” is moved to come before “Part 1” function calls! So this tells me two important things:

1. Currently, if you set a style on a particular cell or cell range that already has a style, if you do not specify _all_ the previous style’s properties then the ones you leave out will be changed back to defaults.
2. Currently, setting a style on an entire row or column will never change any styling for cells that have already had any styles applied to them.

I think it would be more convenient, and make more sense, if it worked like this instead:

1. Setting a style on a cell should not affect the properties of that cell’s style that are not specified. (So setting only a cell’s number format should have no effect on the background color, for example.)
2. When multiple function calls change the same property on any cells, the later function call should always override the earlier one.

Is this feasible?

**Comment by simmone** [comment]
It's a bug indeeded, your expection is just mine, I'll fix it.

**Comment by simmone** [comment]
updated, please verify.
