### ISSUE TITLE
Add support for cell text alignment

### ISSUE THREAD

**Issue by otherjoel** [simmone/racket-simple-xlsx#8]
Set cell horizontal text alignment to one of (for example) `left`, `right`, `center` — and vertical alignment to `top`, `middle`, `bottom`

**Comment by simmone** [comment]
Of cource, I'll do it one by one.

Thank your requirement , this is improving package needed.

**Comment by otherjoel** [comment]
Thank you! No hurry. Glad to help.

**Comment by simmone** [comment]
done, please update and verify.

add two styles: horizontalAlign verticalAlign.

horizontalAlign: 'left 'right 'center

verticalAlign: 'top 'bottom 'middle
