### ISSUE TITLE
Change return type of with-input-from-xlsx-file

### ISSUE THREAD

**Issue by bdeket** [simmone/racket-simple-xlsx#9]
Please change the return type to any (as well for the supplied user-proc)
to be more in line with functions like call-with-input-from-file etc.

making this possible
```
(define sheet-names
  (with-input-from-xlsx-file
   "test.xlsx"
   (λ (xlsx)
     (get-sheet-names xlsx))))
````

**Comment by simmone** [comment]
Updated, Please update the package. Thank you for usage and bug report.

**Comment by simmone** [comment]
package updated.
